version: '3'
services:
  api:
    build: .
    command: bash -c " rake db:setup rake db:schema:load rake db:seed bundle exec rackup --host 0.0.0.0 -p 5000"
    ports:
      - '5000:5000'
    volumes:
      - .:/onboarding_jp
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - .:/onboarding_jp
