default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: db
  pool: 5

development:
  <<: *default
  database: api_dev

test:
  <<: *default
  database: api_test
